name: CLink Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Go Build
        run: |
          go build -v -o ./cLink src/main.go
          chmod +x ./cLink

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${GITHUB_REF#refs/tags/} .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_IMAGE_NAME }}:${GITHUB_REF#refs/tags/}

      - name: Log out from Docker
        run: docker logout
